### AEA2020 ###
##  IV ##

# remove old objects from R working space
rm(list=ls())

####################################################################
#   LOAD PACKAGES  
####################################################################

#Load Packages
# Define packages that you need
packages_vector <- c( "haven", "dplyr",  "sandwich",  "jtools", "data.table",
     				 "fBasics",  "xtable",  "stargazer", "AER", "causalweight")
#install.packages(packages_vector)
lapply(packages_vector, require, character.only = TRUE) 


# Set working directory
getwd()
work_dir <- "Q:/Arbeitsmarktökonomie/Data-Lehre/Methods/2020 Applied Empirical Analysis/Applications/IV/FamilySize/US_census_data"
setwd(work_dir)

####################################################################
#  READ IN AND INSPECT YOUR DATA   
####################################################################

# Read in the data - 1980 PUMS
# Random sample of 1/3 of the observations
data <-read_dta("AngristEvans1980_sample.dta") 
# data <-read_dta("AngristEvans1980_clean.dta") # full data set

data <- as.data.frame(data)

# Overview of data - list of variables and labels

# ageqk           age in quarters, first born
# ageq2nd         age in qtrs second kid
# ageq3rd         age in qtrs of 3rd kid
# kidcount        count of kids in household
# boy1st          first birth boy
# boy2nd          2nd birth boy
# boys2           first two births boys
# girls2          first two births girls
# samesex         first two kids are of same sex
# morekids        had more than 2 kids
# multi2nd        second birth twins
# agem            age in years of mom
# agefstm         age of mom when kid first born
# agefstd         age of dad when kid first born
# aged            age of dad
# blackm          =1 if mom black
# hispm           =1 if mom hispanic
# othracem        =1 if mom other race (white is ref)
# blackd          =1 if dad black
# hispd           =1 if dad hispanic
# othraced        =1 if dad other race (white is ref)
# educm           moms education
# faminc          family income (adjusted)
# weeksm          moms weeks worked
# hourswm         hours per week mom
# weeksd          weeks worked dad
# hourswd         hours per week dad
# workedm         worked for pay mom
# workedd         worked for pay dad
# incomem         moms labour income (adjusted)
# incomed         dads labour income (adjusted)
# lfaminc         log family income (adjusted)
# nonmomi         income not generated by mum (adjusted)
# lnonmomi        log income not generated by mum (adjusted)
# msample         married sample

# Inspect
data_check <- fBasics::basicStats(data) %>% t() %>% as.data.frame() %>% dplyr::select(Mean, Stdev, Minimum, Maximum, nobs, NAs)
print(round(data_check, digits=2))


####################################################################
#  Sample restrictions
####################################################################

	# only keep women aged 21-35, who were older than 15 at first birth
	data <- dplyr::filter(data, agem >= 21 & agem <= 35)
	data <- dplyr::filter(data, agefstm >= 15)	
	# who have 2 or more children
	data <- dplyr::filter(data, kidcount >= 2)
	# second child older than 1 
	data <- dplyr::filter(data, ageq2nd > 4) 

	# selective sample: We dont look at the overall effect of fertility on labour supply. But on the effect of going from 2 to 3 and more children.
	# women aged 21-35 are potentially only having their 3rd child when they are older. The share of individuals that is induced to have a third child 
	# bc of the same sex composition might be underestimated. 

####################################################################
#  Define variables of interest
####################################################################

	# Endogenous Variable
	data$d <- data$morekids # has more than 2 kids
	# Instruments
	data$z <- data$samesex # first two kids are of same sex

	# actually not really necessary if you want to keep the variable names, but possibly useful, if you quickly want to change the instrument

	# store each variable in own R object
	attach(data) 

	# Outcomes
	y_vec <- cbind(workedm, weeksm, hourswm, incomem, lfaminc)
	y_names<- c("workedm", "weeksm", "hourswm", "incomem", "lfaminc")

	# Covariates
	x_desc_names<-c("kidcount", "morekids", "boy1st", "boy2nd", "boys2", "girls2", "samesex", 
				"multi2nd", "agem" ,"aged", "agefstm", "agefstd", "workedm", "workedd", "weeksm", 
				"weeksd", "hourswm", "hourswd", "incomem", "incomed", "faminc", "nonmomi") 


####################################################################
#  DESCRIPTIVE STATISTICS   
####################################################################

	# Replicate Table 2 (page 445) for 1980 data
	# whole sample
	desc <- fBasics::basicStats(data[x_desc_names]) %>% t() %>% as.data.frame() %>% dplyr::select(Mean, Stdev, nobs)
	print(round(desc, digits=2))


####################################################################
#  Check balancedness in covariates by instrument value
####################################################################

	# regress istrument on characteristics
	diff.m <- lm(z ~  agem + agefstm + blackm + hispm + othracem + educm)
	cov <- vcovHC(diff.m, type = "HC")
	robust.se.diff.m <- sqrt(diag(cov))

	# Output Difference in means
	stargazer(diff.m, se=list(robust.se.diff.m), 
	            keep.stat = c("n"), 
	            align=TRUE, dep.var.labels = c("Difference by same sex"), dep.var.labels.include = TRUE)


####################################################################
#  First stage
####################################################################


ols.m.morekids.1 <- lm(d ~ samesex )
cov <- vcovHC(ols.m.morekids.1, type = "HC")
robust.se.morekids.1 <- sqrt(diag(cov))

ols.m.morekids.2 <- lm(d ~ boy1st + boy2nd + samesex + agem + agefstm + blackm + hispm + othracem)
cov <- vcovHC(ols.m.morekids.2, type = "HC")
robust.se.morekids.2 <- sqrt(diag(cov))


# Output Coefficients
stargazer(ols.m.morekids.1,ols.m.morekids.2, se=list(robust.se.morekids.1, robust.se.morekids.2), 
            keep=c("boy1st", "boy2nd", "samesex", "boys2", "girls2"  ), keep.stat = c("n", "rsq", "f"), 
            align=TRUE, dep.var.labels = c("More than one child"), dep.var.labels.include = TRUE)

# women with same sex children are 6.1 pp more likely to have a third child = complier population
# column 2 and 4 control for gender of the first and second child to avoid potential endogeneity concerns related to the sex of the children

# describe complier population?


####################################################################
#  Wald Estimate / LATE
####################################################################

# See Table 5 (first 2 columns)
# Manually exemplary for workedm (full sample)

# conditional outcomes (for participation decision)
E_workedm_1 = mean(workedm[z==1])
E_workedm_0 = mean(workedm[z==0])

# conditional treatment
E_d_1 = mean(d[z==1])
E_d_0 = mean(d[z==0])

# difference in conditional outcomes
diff_workedm = E_workedm_1 - E_workedm_0

# diff_workedm_m <- summary(lm(workedm~z))
# diff_workedm_coeff <- diff_workedm_m$coefficients[2,1] #standard errors - not robust ones though
# diff_workedm_se <- diff_workedm_m$coefficients[2,2]

# difference in conditional treatment = FIRST STAGE
diff_d = E_d_1 - E_d_0 

# diff_d_m <- summary(lm(d~z))
# diff_d_coeff <- diff_d_m$coefficients[2,1]
# diff_d_se <- diff_d_m$coefficients[2,2]

# Wald estimator
wald_workedm = diff_workedm/diff_d # standard errors?

# having more than 2 children reduces LS by 13.3 pc points

# simple table
tab_wald <- rbind(cbind(E_workedm_1, E_workedm_0, diff_workedm ), cbind(E_d_1, E_d_0, diff_d), cbind(NA, NA,wald_workedm ))
colnames(tab_wald) <- c("Z=1", "Z=0", "Difference")
rownames(tab_wald) <- c("E(Y|Z)", "E(D|Z)", "Wald estimator")
xtable(tab_wald, digits =3)

# this effect is valid for the complier population - if homogeneous also for other groups

####################################################################
#  Two stage least squares estimation
####################################################################

#define vector of controls
x <- cbind(boy1st, boy2nd, agem, agefstm, blackm, hispm, othracem)

# Reduced from regression or ITT

itt.model <- function(y){
							itt.m <- lm(y ~ z + x)
							cov <- vcovHC(itt.m, type = "HC")
							robust.se <- sqrt(diag(cov))
							list( itt.coeff = itt.m$coefficients[2], robust.se = robust.se[2], pval = 2*pnorm(-abs(itt.m$coefficients[2]/robust.se[2])) )
						}

itt_output <- apply(y_vec, 2, itt.model)

# convert list to table
itt_output<-rbindlist(itt_output)
rownames(itt_output)<- y_names

# plot table
xtable(itt_output, digits=3)


# OLS (Table 7, column 1)

ols.model <- function(y){
							ols.m <- lm(y ~ d + x)
							cov <- vcovHC(ols.m, type = "HC")
							robust.se <- sqrt(diag(cov))
							list( ols.coeff = ols.m$coefficients[2], robust.se = robust.se[2], pval = 2*pnorm(-abs(ols.m$coefficients[2]/robust.se[2])))
						}

ols_output <- apply(y_vec, 2, ols.model)

# convert list to table
ols_output<-rbindlist(ols_output)


# 2SLS (Table 7, column 2)

# ivreg package exemplarily for workedm
iv.m <- ivreg(workedm ~ d + x  | z + x)
summary(iv.m, vcov = sandwich, diagnostics = TRUE)

# important: Endogenous variables (X) can only appear before the vertical line; 
# instruments (Z) can only appear after the vertical line; 
# exogenous regressors that are not instruments (W) must appear both before and after the vertical line.


tsls.model <- function(y){
							iv.m <- ivreg(y ~ d + x  | z + x)
							iv_sum <-summary(iv.m, vcov = sandwich)
							list( iv.coeff = iv_sum$coefficients[2,1], robust.se = iv_sum$coefficients[2,2], pval = 2*pnorm(-abs(iv_sum$coefficients[2,1]/iv_sum$coefficients[2,2])))
							}

iv_output <- apply(y_vec, 2, tsls.model)

# convert list to table
iv_output<-rbindlist(iv_output)

# join OLS and IV output
output<-cbind(ols_output,iv_output)
rownames(output)<- y_names

# plot table
xtable(output, digits=3)

# IV estimates smaller than corresponding OLS estimates. OLS seems to overestimate the response of women to having more children.
# Parametric estimation assumes assumes effect homogeneity

####################################################################
# Semiparametric LATE
####################################################################


# 1. Estimate probit for Pr(Z = 1| X = x) and calculate predicted probabilities phat(x).
# 2. Estimate nonparametric regression to obtain
# 		E[D | phat(x) = p;Z = z]
# 		E[Y | phat(x) = p;Z = z].
# 3. Bootstrap everything for inference.

# estimate pscores manually
pscore.model <- glm(z ~ x, family = binomial(link = "probit"))
summ(pscore.model, , robust = "HC1")

data$pscore <- pscore.model$fitted.values 
data$z_labelled <- factor(z, levels = c(0,1), label = c("Z=0", "Z=1")) 

# Check for common support in propensity score - not really overlapping - how can that be???
ggplot(data, aes(x = pscore, fill = z_labelled)) + geom_density(alpha=0.4)  + theme_classic() + xlim(0, 1)

# use causalweight package (increase boot to 199 or higher) - see Bodory and Huber (2018) The causalweight Package
late_workedm <- lateweight(y=workedm, d=d, z=z, x=x, LATT=FALSE,logit=FALSE,boot=19)

# display results
cat("LATE: ",round(c(late_workedm$effect),3),", standard error: ",
				+ round(c(late_workedm$se.effect),3), ", p-value: ",
				+ round(c(late_workedm$pval.effect),3))

# for all outcomes
sp.model <- function(y){
						sp.m <- lateweight(y=y, d=d, z=z, x=x, LATT=FALSE,logit=FALSE,boot=19)
						list( sp.iv.coeff = sp.m$effect, boot.se = sp.m$se.effect, pval = sp.m$pval.effect)
						}

sp.iv_output <- apply(y_vec, 2, sp.model)

# convert list to table
sp.iv_output<-rbindlist(sp.iv_output)


# join with OLS and IV output
output_all<-cbind(output, sp.iv_output)
rownames(output_all)<- y_names

# plot table
xtable(output_all, digits=3)


	# Discuss finings: Overall we find a negative effect on LS from having a third child for women
	# Semiparametric and parametric estimates do not differ much


############################################
# Small assignment (second part)
############################################

# NP LATE for the sample of married men

E_workedd_1 = mean(workedd[z==1 & msample ==1 ])
E_workedd_0 = mean(workedd[z==0 & msample ==1])

# conditional treatment
E_d_1 = mean(d[z==1 & msample ==1])
E_d_0 = mean(d[z==0 & msample ==1])

# difference in conditional outcomes
diff_workedd = E_workedd_1 - E_workedd_0

# difference in conditional treatment = FIRST STAGE
diff_d = E_d_1 - E_d_0 

# Wald estimator
wald_workedd = diff_workedd/diff_d # standard errors?

# having more than 2 children reduces LS by 13.3 pc points

# simple table
tab_wald_d <- rbind(cbind(E_workedd_1, E_workedd_0, diff_workedd ), cbind(E_d_1, E_d_0, diff_d), cbind(NA, NA,wald_workedd ))
colnames(tab_wald_d) <- c("Z=1", "Z=0", "Difference")
rownames(tab_wald_d) <- c("E(Y|Z)", "E(D|Z)", "Wald estimator")
xtable(tab_wald_d, digits =3)
